# Site settings
url: https://documentation.codeship.com
baseurl:
permalink: /:categories/:title/
tags_dir: tags
categories_dir: categories
ubuntu_version: trusty
zendesk:
  widget: true
  chat: false

# SEO Tag
title: Codeship Documentation
twitter:
  username: codeship
facebook:
  publisher: https://www.facebook.com/codeship
logo: /assets/img/logo-codeship.png
author: Codeship
social:
  name: Codeship
  links:
    - https://www.twitter.com/codeship
    - https://www.facebook.com/codeship
    - https://www.linkedin.com/company/codeship
    - https://github.com/codeship
    - https://www.instagram.com/codeship/
    - https://vimeo.com/codeship
    - https://www.youtube.com/channel/UCxc5i0d5pIJJeF39NFdCGRQ

# Defaults
defaults:
  - scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: page
      weight: 50
      comments: true
      image: /assets/img/og_documentation.jpg

collections:
  general:
    title: General
    shortname: general
    permalink: /general/:path/
    output: true
  basic:
    title: Codeship Basic
    shortname: basic
    permalink: /basic/:path/
    output: true
  pro:
    title: Codeship Pro
    shortname: pro
    permalink: /pro/:path/
    output: true

# Jekyll
exclude:
  - _*.json
  - bin
  - CODE_OF_CONDUCT.md
  - codeship-services.yml
  - codeship-steps.yml
  - codeship.aes
  - CONTRIBUTING.md
  - deployment.env*
  - dockercfg*
  - Dockerfile*
  - external
  - Gemfile*
  - Guardfile
  - gulpfile.js
  - LICENSE.md
  - node_modules
  - npm-shrinkwrap.json
  - package.json
  - Rakefile
  - README.md
  - SUPPORT.md
  - templates
  - tmp
  - yarn.lock
encoding: utf-8
plugins:
  - jekyll-coffeescript
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-menus
  - shipyard-framework

# SASS
sass:
  sass_dir: _sass
  style: :compressed

# Build settings
markdown: kramdown

# Kramdown
kramdown:
  input: GFM
  hard_wrap: false
  parse_block_html: true
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    line_numbers: false

# Prose.io
# prose:
#   rooturl: '_posts'
#   siteurl: 'https://documentation.codeship.com/'
#   media: 'images'
#   ignore:
#     - index.md
#     - _config.yml
#     - /_layouts
#     - /_includes
#   metadata:
#     _posts:
#       - name: 'layout'
#         field:
#           element: 'hidden'
#           value: 'page'
#       - name: 'title'
#         field:
#           element: 'text'
#           label: 'Page Title'
#       - name: 'categories'
#         field:
#           element: 'select'
#           label: 'Category'
#           options: 'https://documentation.codeship.com/metadata/categories.jsonp'
#       - name: 'tags'
#         field:
#             element: 'multiselect'
#             label: 'Tags'
#             placeholder: 'Choose Tags'
#             alterable: true
#             options: 'http://documentation.codeship.com/metadata/tags.jsonp'
#       - name: 'weight'
#         field:
#           element: 'number'
#           label: 'Page Weight'
#           help: 'Used for sorting subpages in listings'
#           value: 50
