# Site settings
url: https://documentation.codeship.com
baseurl:
permalink: /:categories/:title/
tags_dir: tags
ubuntu_version: trusty
zendesk:
  widget: true
  chat: false

# SEO Tag
title: Codeship Documentation
twitter:
  username: codeship
facebook:
  publisher: https://www.facebook.com/codeship
logo: /assets/img/logo-codeship.png

# Defaults
defaults:
  - scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: page
      weight: 50
      comments: true
      image: /assets/img/og_documentation.jpg
  - scope:
      path: "_basic/analytics"
    values:
      category: "Analytics"
  - scope:
      path: "_basic/continuous-deployment"
    values:
      category: "Continuous Deployment"
  - scope:
      path: "_basic/continuous-integration"
    values:
      category: "Continuous Integration"
  - scope:
      path: "_basic/quickstart"
    values:
      category: "Quickstart"
  - scope:
      path: "_basic/languages-frameworks"
    values:
      category: "Languages &amp; Frameworks"
  - scope:
      path: "_basic/queues"
    values:
      category: "Queues"
  - scope:
      path: "_basic/services"
    values:
      category: "Services"
  - scope:
      path: "_basic/databases"
    values:
      category: "Databases"
  - scope:
      path: "_basic/builds-and-configuration"
    values:
      category: "Builds &amp; Configuration"
  - scope:
      path: "_pro/continuous-deployment"
    values:
      category: "Continuous Deployment"
  - scope:
      path: "_pro/continuous-integration"
    values:
      category: "Continuous Integration"
  - scope:
      path: "_pro/quickstart"
    values:
      category: "Quickstart"
  - scope:
      path: "_pro/builds-and-configuration"
    values:
      category: "Builds &amp; Configuration"
  - scope:
      path: "_pro/languages-frameworks"
    values:
      category: "Languages &amp; Frameworks"
  - scope:
      path: "_general/about"
    values:
      category: "About"
  - scope:
      path: "_general/account"
    values:
      category: "Account"
  - scope:
      path: "_general/account/guides"
    values:
      category: "Guides"
  - scope:
      path: "_general/projects"
    values:
      category: "Projects"

sidebar_order:
  - "Quickstart"
  - "Builds &amp; Configuration"
  - "Languages &amp; Frameworks"
  - "Databases"
  - "Continuous Deployment"
  - "Continuous Integration"
  - "Analytics"
  - "Queues"
  - "Services"
  - "About"
  - "Account"
  - "Guides"
  - "Projects"

collections:
  general:
    title: General
    shortname: general
    permalink: /general/:path/
    sort_order: 1
    output: true
  basic:
    title: Codeship Basic
    shortname: basic
    permalink: /basic/:path/
    sort_order: 2
    output: true
  pro:
    title: Codeship Pro
    shortname: pro
    permalink: /pro/:path/
    sort_order: 3
    output: true

# Jekyll
exclude:
  - _*.json
  - bin
  - CODE_OF_CONDUCT.md
  - codeship-services.yml
  - codeship-steps.yml
  - codeship.aes
  - CONTRIBUTING.md
  - external
  - Gemfile*
  - Guardfile
  - gulpfile.js
  - LICENSE.md
  - node_modules
  - npm-shrinkwrap.json
  - package.json
  - README.md
  - templates
encoding: utf-8
gems:
  - jekyll-coffeescript
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-redirect-from

# SASS
sass:
  sass_dir: _sass
  style: :compressed

# Build settings
markdown: kramdown

# Kramdown
kramdown:
  input: GFM
  hard_wrap: false
  parse_block_html: true
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    line_numbers: false

# Prose.io
# prose:
#   rooturl: '_posts'
#   siteurl: 'https://documentation.codeship.com/'
#   media: 'images'
#   ignore:
#     - index.md
#     - _config.yml
#     - /_layouts
#     - /_includes
#   metadata:
#     _posts:
#       - name: 'layout'
#         field:
#           element: 'hidden'
#           value: 'page'
#       - name: 'title'
#         field:
#           element: 'text'
#           label: 'Page Title'
#       - name: 'categories'
#         field:
#           element: 'select'
#           label: 'Category'
#           options: 'https://documentation.codeship.com/metadata/categories.jsonp'
#       - name: 'tags'
#         field:
#             element: 'multiselect'
#             label: 'Tags'
#             placeholder: 'Choose Tags'
#             alterable: true
#             options: 'http://documentation.codeship.com/metadata/tags.jsonp'
#       - name: 'weight'
#         field:
#           element: 'number'
#           label: 'Page Weight'
#           help: 'Used for sorting subpages in listings'
#           value: 50
